# Generated by Django 4.2.3 on 2025-06-18 07:27

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, verbose_name='项目名')),
                ('what', models.TextField(verbose_name='项目描述')),
                ('why', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='项目意义')),
                ('priority', models.IntegerField(choices=[(0, '不重要不紧急'), (1, '不重要紧急'), (2, '重要不紧急'), (3, '重要紧急')], default=0, verbose_name='优先级')),
                ('public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('start_date', models.DateField(verbose_name='计划开始日期')),
                ('end_date', models.DateField(verbose_name='计划完成日期')),
                ('how', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='执行步骤')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='附件')),
                ('status', models.BooleanField(default=False, verbose_name='是否完成')),
                ('think', models.TextField(blank=True, null=True, verbose_name='项目感想')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
    ]
