# Generated by Django 4.2.3 on 2026-01-27 02:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='what',
            field=models.TextField(blank=True, null=True, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='why',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='项目意义'),
        ),
    ]
