# Generated by Django 4.2.3 on 2026-01-27 02:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectmodel_what_alter_projectmodel_why'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='how',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='执行步骤'),
        ),
    ]
