# Generated by Django 4.2.27 on 2026-01-30 19:45

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectmodel_how'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='how',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='执行步骤'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='why',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='项目意义'),
        ),
    ]
