# Generated by Django 4.2.27 on 2026-03-20 16:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectmodel_how_alter_projectmodel_why'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='ck4_test',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='CKEditor4测试'),
        ),
    ]
