# Generated by Django 4.2.27 on 2026-03-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectmodel_ck4_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='ck4_test',
        ),
    ]
