# Generated by Django 4.2.2 on 2023-07-15 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='项目名')),
                ('what', models.TextField(verbose_name='项目描述')),
                ('why', models.TextField(verbose_name='项目意义')),
                ('end_time', models.DateField(verbose_name='项目结束日期')),
                ('how', models.TextField(verbose_name='执行步骤')),
                ('status', models.BooleanField(default=False, verbose_name='项目状态')),
                ('think', models.TextField(blank=True, null=True, verbose_name='项目感想')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
