# Generated by Django 4.2.3 on 2023-07-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='end_time',
            field=models.DateField(verbose_name='计划完成日期'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
    ]
