# Generated by Django 4.2.2 on 2023-07-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_projectmodel_end_time_alter_projectmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='priority',
            field=models.IntegerField(choices=[(0, '低'), (1, '中'), (2, '高')], default=0, verbose_name='优先级'),
        ),
    ]
