# Generated by Django 4.2.3 on 2023-07-17 23:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_projectmodel_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='how',
            field=tinymce.models.HTMLField(verbose_name='计划完成日期'),
        ),
    ]
