# Generated by Django 4.2.3 on 2023-07-17 23:50

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_projectmodel_how'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='how',
            field=markdownx.models.MarkdownxField(verbose_name='计划完成日期'),
        ),
    ]
