# Generated by Django 4.2.3 on 2023-07-17 23:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_projectmodel_how'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='how',
            field=ckeditor.fields.RichTextField(verbose_name='计划完成日期'),
        ),
    ]
