# Generated by Django 4.2.3 on 2023-07-18 00:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_projectmodel_how'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='how',
            field=ckeditor.fields.RichTextField(verbose_name='执行步骤'),
        ),
    ]
