# Generated by Django 4.2.3 on 2023-07-18 00:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_projectmodel_how'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='how',
            field=tinymce.models.HTMLField(verbose_name='执行步骤'),
        ),
    ]
