# Generated by Django 4.2.3 on 2023-07-18 00:12

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_projectmodel_how'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='how',
            field=markdownx.models.MarkdownxField(verbose_name='执行步骤'),
        ),
    ]
