# Generated by Django 4.2.3 on 2023-07-19 13:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_projectmodel_how'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='how',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='执行步骤'),
        ),
    ]
