# Generated by Django 4.2.3 on 2023-07-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_projectmodel_attachments_alter_projectmodel_how'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='attachments',
        ),
    ]
