# Generated by Django 4.2.3 on 2023-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_projectmodel_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='附件'),
        ),
    ]
