# Generated by Django 4.2.3 on 2023-07-20 18:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_projectmodel_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='why',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='项目意义'),
        ),
    ]
