# Generated by Django 4.2.3 on 2023-07-20 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_projectmodel_why'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='计划开始日期'),
            preserve_default=False,
        ),
    ]
