# Generated by Django 4.2.3 on 2023-07-21 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_rename_end_time_projectmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': ['status', '-priority', 'end_date'], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
    ]
