# Generated by Django 4.2.3 on 2024-05-11 09:43

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_projectmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='public',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='how',
            field=mdeditor.fields.MDTextField(verbose_name='执行步骤'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='priority',
            field=models.IntegerField(choices=[(0, '不重要不紧急'), (1, '不重要紧急'), (2, '重要不紧急'), (3, '重要紧急')], default=0, verbose_name='优先级'),
        ),
    ]
