# Generated by Django 4.2.3 on 2023-07-30 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_projectmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
    ]
