# Generated by Django 4.2.3 on 2024-05-14 17:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_projectmodel_options_projectmodel_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='how',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='执行步骤'),
        ),
    ]
