# Generated by Django 4.2.3 on 2024-06-19 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0019_weekly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.CreateModel(
            name='UserForWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
