# Generated by Django 4.2.3 on 2024-06-20 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_weekly_date_userforweekly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userforweekly',
            options={'verbose_name': '周刊用户', 'verbose_name_plural': '周刊用户'},
        ),
        migrations.AlterField(
            model_name='weekly',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True, verbose_name='创建日期'),
        ),
    ]
