# Generated by Django 4.2.3 on 2024-06-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_userforweekly_options_alter_weekly_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforweekly',
            name='life',
            field=models.PositiveSmallIntegerField(default=75, verbose_name='预期寿命'),
        ),
    ]
