# Generated by Django 4.2.3 on 2024-06-24 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_userforweekly_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='创建日期'),
        ),
    ]
