# Generated by Django 4.2.3 on 2025-06-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_userforweekly_create_time_userforweekly_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='月租金'),
        ),
        migrations.AlterField(
            model_name='houseitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价'),
        ),
    ]
