# Generated by Django 4.2.3 on 2025-06-18 07:27

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='周刊内容')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='附件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '周刊',
                'verbose_name_plural': '周刊',
            },
        ),
        migrations.CreateModel(
            name='UserForWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('life', models.PositiveSmallIntegerField(default=75, verbose_name='预期寿命')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '周刊用户',
                'verbose_name_plural': '周刊用户',
            },
        ),
    ]
