# Generated by Django 4.2.3 on 2025-06-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userforweekly',
            table='web_userforweekly',
        ),
        migrations.AlterModelTable(
            name='weekly',
            table='web_weekly',
        ),
    ]
