# Generated by Django 4.2.27 on 2026-01-30 19:45

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0003_userforweekly_create_time_userforweekly_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='周刊内容'),
        ),
    ]
