# Generated by Django 4.2.3 on 2025-06-20 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='房屋名称')),
                ('address', models.TextField(verbose_name='地址')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='面积(m²)')),
                ('public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('status', models.CharField(choices=[('available', '可租'), ('rented', '已租'), ('maintenance', '维修中')], default='available', max_length=20, verbose_name='状态')),
                ('monthly_expense', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='月支出')),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='月租金')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '房屋',
                'verbose_name_plural': '房屋',
            },
        ),
        migrations.CreateModel(
            name='HouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='物品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('condition', models.CharField(choices=[('good', '良好'), ('damaged', '损坏'), ('lost', '丢失')], default='good', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='house.house', verbose_name='所属房屋')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
            },
        ),
    ]
