# Generated by Django 4.2.3 on 2025-06-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': '房屋', 'verbose_name_plural': '房屋'},
        ),
        migrations.AlterModelOptions(
            name='houseitem',
            options={'verbose_name': '物品', 'verbose_name_plural': '物品'},
        ),
        migrations.AlterModelTable(
            name='house',
            table='web_house',
        ),
        migrations.AlterModelTable(
            name='houseitem',
            table='web_houseitem',
        ),
    ]
