# Generated by Django 4.2.3 on 2025-06-20 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0002_alter_house_options_alter_houseitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='public',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houseitem',
            name='public',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
    ]
