"""
Django settings for project_sys project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^d#t&84#_++lxf&f-db3%#ts5r!nj#9el%u*o*$ttk$&&%t-m='

# SECURITY WARNING: don't run with debug turned on in production!

# DEBUG = os.getenv('DJANGO_DEBUG', False)
DEBUG = True

print("DEBUG:", DEBUG)
ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'http://*',
    'https://*',
]

CORS_ORIGIN_WHITELIST = [
    # 其他受信任的来源
]
# Application definition

INSTALLED_APPS = [
    # 个性主题设置
    # 'jazzmin',
    # 'simpleui',
    
    # 'django_daisy',
    
    # 'admin_interface',
    # 'colorfield',  # 用于颜色选择器
    
    'django.contrib.admindocs', # 管理文档
    'django.contrib.admin', 
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.humanize', # 人性化显示

    'django_ckeditor_5',
    'tinymce',

    'markdownx',
    'mdeditor',
    'vditor',

    'import_export',
    
    # 'web',
    'apps.core',
    'apps.projects',
    'apps.weekly',
    'apps.house',
    'apps.user',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'web.middleware.AdminRegisterMiddleware',
]

ROOT_URLCONF = 'project_sys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_sys.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # 重复性验证
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }

    },
    # 是否是常用密码
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # 是否只包含数字
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / 'collected_static'

# 配置 WhiteNoise 用于生产环境静态文件服务
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# WhiteNoise配置
WHITENOISE_MAX_AGE = 30*24*60*60  # 1 月的缓存
WHITENOISE_SKIP_COMPRESS_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'gz', 'tgz', 'bz2', 'xz', 'br']
# 跳过一些特定文件的处理
# WHITENOISE_SKIP_PATHS = ['dist/js/mathjax/', 'admin/js/', 'ckeditor/', 'tinymce/']
WHITENOISE_SKIP_PATHS = ['dist/js/mathjax/', 'ckeditor/', 'tinymce/'] # TODO： check

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

WEB_TITLE = '项目管理系统'

MARKDOWNX_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.extra',
    'markdown.extensions.toc',
    'markdown.extensions.nl2br',
    'markdown.extensions.codehilite',
]
# MARKDOWNX_MARKDOWN_EXTENSION_CONFIGS = {
#     'extra': {
#         'footnotes': {
#             'UNIQUE_IDS': True
#         },
#         'fenced_code': {
#             'lang_prefix': 'lang-'
#         }
#     },
#     'toc': {
#         'permalink': True
#     }
# }
MARKDOWNX_MEDIA_PATH = 'markdownx/'
MARKDOWNX_IMAGE_MAX_SIZE = {
    'size': (5000, 5000),
    'quality': 90
}

# X_FRAME_OPTIONS = 'SAMEORIGIN'  # django3.0
MDEDITOR_CONFIGS = {
    'default': {
        'width': '90% ',  # Custom edit box width
        'height': 500,  # Custom edit box height
        'toc': True,
        'tocm': True,
        'toolbar': [
            "undo", "redo", "|",
            "bold", "del", "italic", "quote", "ucwords", "uppercase", "lowercase", "|",
            "h1", "h2", "h3", "h5", "h6", "|",
            "list-ul", "list-ol", "hr", "|",
            "link", "reference-link", "image", "code", "preformatted-text", "code-block", "table", "datetime",
            "emoji", "html-entities", "pagebreak", "goto-line", "|",
            "help", "info",
            "||", "preview", "watch", "fullscreen"
        ],  # custom edit box toolbar
        # 'upload_image_url': '/media/',
        # image upload format type
        'upload_image_formats': ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
        'image_folder': 'editor',  # image save the folder name
        'theme': 'default',  # edit box theme, dark / default
        'preview_theme': 'default',  # Preview area theme, dark / default
        'editor_theme': 'default',  # edit area theme, pastel-on-dark / default
        'toolbar_autofixed': True,  # Whether the toolbar capitals
        'search_replace': True,  # Whether to open the search for replacement
        'emoji': True,  # whether to open the expression function
        'tex': True,  # whether to open the tex chart function
        'flow_chart': True,  # whether to open the flow chart function
        'sequence': True,  # Whether to open the sequence diagram function
        'watch': True,  # Live preview
        'lineWrapping': False,  # lineWrapping
        'lineNumbers': False,  # lineNumbers
        'language': 'zh'  # zh / en / es
    }

}


# CKEditor 5 配置
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'link', '|',
            'bulletedList', 'numberedList', '|',
            'imageUpload', 'blockQuote', 'insertTable', '|',
            'undo', 'redo'
        ],
        'language': 'zh-cn',
        'image': {
            'upload': {
                'types': ['jpeg', 'png', 'gif', 'bmp', 'webp'],
            }
        },
    },
}

CKEDITOR_5_FILE_UPLOAD_UPLOAD = 'uploads/'

VDITOR_CONFIGS = {  # remember to write "' '"
    'default': {
        "width": "%90",  # use numbers or percentages
        "height": 360,  # use numbers
        "preview_theme": "light",  # can fill in dark, light, wechat
        "typewriterMode": "True",  # whether to enable typewriter mode
        "mode": "ir",  # optional modes: sv, ir, wysiwyg
        "debugger": "false",  # whether to show log
        "value": "",  # editor initialization value
        "theme": "classic",  # can fill in classic, dark
        "icon": "ant",  # canfill in ant, material
        "outline": "false",  # show outline
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 创建log文件的文件夹
LOG_PATH = BASE_DIR / "logs"
LOG_PATH.mkdir(parents=True, exist_ok=True)
# 配置日志
LOGGING = {
    'version': 1,  # 保留字
    'disable_existing_loggers': False,  # 禁用已经存在的logger实例
    # 日志文件的格式
    'formatters': {
        # 详细的日志格式
        'standard': {
            'format': '[%(asctime)s][%(threadName)s:%(thread)d][task_id:%(name)s][%(filename)s:%(lineno)d][%(levelname)s][%(message)s]'
        },
        # 简单的日志格式
        'simple': {
            'format': '[%(levelname)s][%(asctime)s][%(filename)s:%(lineno)d] %(message)s',
            # 'format': '[%(levelname)s][%(asctime)s][%(funcName)s:%(lineno)d] %(message)s',
            # 'format': '[%(levelname)s][%(asctime)s][%(pathname)s:%(lineno)d] %(message)s',
        },
    },
    # 过滤器
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    # 处理器
    'handlers': {
        'console': {     # 在终端打印
            'level': 'DEBUG',
            'filters': ['require_debug_true'],  # 只有在Django debug为True时才在屏幕打印日志
            'class': 'logging.StreamHandler',  #
            'formatter': 'simple',
        },
        'default': {    # 默认的
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',  # 保存到文件，自动切
            'filename': LOG_PATH / "all.log",  # 日志文件
            'backupCount': 3,                                # 最多备份几个
            'formatter': 'simple',
            'encoding': 'utf-8',
            'maxBytes': 1024 * 1024 * 5,                    # 日志大小 5M
        },
        'default_time': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',  # 保存到文件，自动切
            'filename': LOG_PATH / "all_time.log",  # 日志文件
            'backupCount': 5,
            'formatter': 'simple',
            'encoding': 'utf-8',

            'when': 'midnight',  # 每天切
            'interval': 1,  # 每隔一天切
            'delay': True,  # 延迟1秒，等待Django启动

        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,  # 向不向 父logger传递
        },
        'pj': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    }
}

# email setting
EMAIL_USE_SSL = True
EMAIL_PORT = 465
EMAIL_HOST = 'smtp.qq.com'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LOGIN_URL = '/admin/login/'  # For PasswordResetCompleteView


try:
    from .local_settings import *  # 最后导入本地配置
except ImportError:
    pass
