"""
Django settings for project_sys project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^d#t&84#_++lxf&f-db3%#ts5r!nj#9el%u*o*$ttk$&&%t-m='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'http://134.175.124.152'
]

CORS_ORIGIN_WHITELIST = [
    'http://134.175.124.152',
    # 其他受信任的来源
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'ckeditor',
    'ckeditor_uploader',  # 带图片上传的ckeditor
    'tinymce',

    'markdownx',
    'mdeditor',

    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project_sys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_sys.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # 重复性验证
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }

    },
    # 是否是常用密码
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # 是否只包含数字
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

# USE_TZ = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'collected_static'  # 生成环境 使用 collection

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

MARKDOWNX_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.extra',
    'markdown.extensions.nl2br',
    'markdown.extensions.codehilite',
]
MARKDOWNX_MEDIA_PATH = 'markdownx/'
MARKDOWNX_IMAGE_MAX_SIZE = {
    'size': (5000, 5000),
    'quality': 90
}

# X_FRAME_OPTIONS = 'SAMEORIGIN'
# MDEDITOR_CONFIGS = {
#     'default':{
#         'width': '90% ',  # Custom edit box width
#         'height': 500,  # Custom edit box height
#         'toolbar': [
#             "undo", "redo", "|",
#             "bold", "del", "italic", "quote", "ucwords", "uppercase", "lowercase", "|",
#             "h1", "h2", "h3", "h5", "h6", "|",
#             "list-ul", "list-ol", "hr", "|",
#             "link", "reference-link", "image", "code", "preformatted-text", "code-block", "table", "datetime",
#             "emoji", "html-entities", "pagebreak", "goto-line", "|",
#             "help", "info",
#             "||", "preview", "watch", "fullscreen"
#         ],  # custom edit box toolbar
#         # 'upload_image_url': '/media/',
#         'upload_image_formats': ["jpg", "jpeg", "gif", "png", "bmp", "webp"],  # image upload format type
#         'image_folder': 'editor',  # image save the folder name
#         'theme': 'default',  # edit box theme, dark / default
#         'preview_theme': 'default',  # Preview area theme, dark / default
#         'editor_theme': 'default',  # edit area theme, pastel-on-dark / default
#         'toolbar_autofixed': True,  # Whether the toolbar capitals
#         'search_replace': True,  # Whether to open the search for replacement
#         'emoji': True,  # whether to open the expression function
#         'tex': True,  # whether to open the tex chart function
#         'flow_chart': True,  # whether to open the flow chart function
#         'sequence': True, # Whether to open the sequence diagram function
#         'watch': True,  # Live preview
#         'lineWrapping': False,  # lineWrapping
#         'lineNumbers': False,  # lineNumbers
#         'language': 'zh'  # zh / en / es
#     }
#
# }


CKEDITOR_UPLOAD_PATH = "uploads/"  # 文件保存为止，因为上边配置了media， 图片将保存至media/uploads下
CKEDITOR_RESTRICT_BY_USER = True  # 是否限制用户访问
# CKEDITOR_JQUERY_URL = 'https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js'  # 使用jquery库
# CKEDITOR_UPLOAD_SLUGIFY_FILENAME = False
CKEDITOR_IMAGE_BACKEND = 'pillow'  # 图片上传使用pillow插件

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', 'Preview', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
            '/',  # put this to force next toolbar on new line
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            # {'name': 'paragraph',
            #  'items': ['NumberedList', 'BulletedList', '-',
            #            'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']},
            #
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'CodeSnippet', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak',
                       'Iframe']},
            '/',  # put this to force next toolbar on new line
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'styles', 'items': ['Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},

        ],

        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
        # 'height': 291,
        # 'width': '100%',
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage',  # the upload image feature
            # your extra plugins here
            # 'image2',  # simplified image upload plugin
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',

            # 移除右键菜单相关的插件

        ]),
        # 'removePlugins': ','.join([
        #     'menubutton',  # 移除菜单按钮插件
        #     'contextmenu',  # 移除右键菜单插件
        #     'liststyle',
        #     'tabletools',
        # ]),
        # 'startupFocus': True,
        # 'touchenabled': False,
    }
}
# CKEDITOR_BROWSE_SHOW_DIRS = True  # 显示目录浏览
# CKEDITOR_ALLOW_NONIMAGE_FILES = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

try:
    from .local_settings import *  # 最后导入本地配置
except ImportError:
    pass
